### ISSUE TITLE
Solar Logo

### ISSUE THREAD

**Issue by HansenSAndrew** [TheSalmanK/343-s23-p1#6]
I'm working on a lab computer, and the "Solar" logo looks funky on Linux. Maybe it's because it's on Firefox?

**Comment by TheSalmanK** [comment]
Can you send me a picture on discord?

**Comment by HansenSAndrew** [comment]
It's because the font used for "S__LAR" is not installed on every computer. Here are some safe fonts, but they need tinkering with the size/dimensions. https://web.mit.edu/jmorzins/www/fonts.html

**Comment by TheSalmanK** [comment]
Okay, we can change it to something that works cross platform. If you can't do it in code I'll make a new SVG with a safe font for it.
